name: Deploy AWS Lambda
on:
  push:
    branches:
      - main
    paths:
      - "lambda/**"

jobs:
  deploy: # name of deploy job
    runs-on: ubuntu-latest # Sets the OS for the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python # Sets up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt lambda/

      - name: Configure AWS Creds # Sets up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "eu-west-1"

      - name: Deploy Lambda function # zips lambda directory and updates lambda function
        run: |
          cd lambda
          zip -r ../lambda_function.zip .
          aws lambda update-function-code --function-name cicd-test-lambda --zip-file fileb://../lambda_function.zip
